### ISSUE TITLE
[BUG][Android] Emoji not supported on Confirmation alert

### ISSUE THREAD

**Issue by cuzik** [magrathealabs/flipermercado#8]
## Hi hi :alien: 

This confirmation message has a not supported emoji when we try use this in android device.

![WhatsApp Image 2019-09-17 at 12 38 28](https://user-images.githubusercontent.com/17733336/65057029-55b04980-d948-11e9-88b9-9c0d98f9f3c5.jpeg)

**Comment by izn** [comment]
Invalid.
